# Generated by Django 2.0.7 on 2018-11-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='assigned_year',
            field=models.CharField(default='', max_length=10, verbose_name='配属された年度'),
        ),
        migrations.AddField(
            model_name='member',
            name='current_year',
            field=models.CharField(default='2018', max_length=10, verbose_name='現在の年度'),
        ),
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.CharField(choices=[('教授', '教授'), ('准教授', '准教授'), ('D3', 'D3'), ('D2', 'D2'), ('D1', 'D1'), ('M2', 'M2'), ('M1', 'M1'), ('B4', 'B4')], default='', max_length=3, verbose_name='身分'),
        ),
        migrations.AddField(
            model_name='member',
            name='progress',
            field=models.CharField(default='', max_length=50, verbose_name='進路'),
        ),
        migrations.AddField(
            model_name='member',
            name='text',
            field=models.CharField(default='', max_length=100, verbose_name='一言'),
        ),
    ]
