# Generated by Django 2.0.7 on 2018-11-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20181112_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='assigned_year',
            field=models.CharField(default='', max_length=4, verbose_name='配属された年度'),
        ),
        migrations.AlterField(
            model_name='member',
            name='current_year',
            field=models.CharField(default='2018', max_length=4, verbose_name='現在の年度'),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(choices=[('0', '教授'), ('1', '准教授'), ('2', '助教授'), ('3', '技術職員'), ('4', 'PD'), ('5', 'D3'), ('6', 'D2'), ('7', 'D1'), ('8', 'M2'), ('9', 'M1'), ('10', 'B4')], default='', max_length=3, verbose_name='身分'),
        ),
    ]
