# Generated by Django 2.0.7 on 2018-11-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20181112_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='text',
        ),
        migrations.AddField(
            model_name='member',
            name='hobby',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='趣味'),
        ),
        migrations.AlterField(
            model_name='member',
            name='progress',
            field=models.CharField(blank=True, default='宮崎大学工学部→', max_length=50, verbose_name='進路'),
        ),
    ]
