# Generated by Django 2.0.7 on 2018-11-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20181116_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='birthplace',
            field=models.CharField(blank=True, max_length=20, verbose_name='出身地'),
        ),
    ]
