# Generated by Django 2.1.2 on 2018-11-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20181116_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='pic/no_image.jpg', upload_to='media/', verbose_name='写真'),
        ),
    ]
