# Generated by Django 2.0.7 on 2018-11-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20181119_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../../media/media/universe-2742113_1280.jpg', upload_to='media/', verbose_name='写真'),
        ),
    ]
