# Generated by Django 2.0.7 on 2018-11-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20181119_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='media/no_image.jpg', upload_to='media/', verbose_name='写真'),
        ),
    ]
