# Generated by Django 2.0.7 on 2018-11-19 15:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20181120_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('text', models.TextField(verbose_name='本文')),
                ('thumnail', models.ImageField(blank=True, null=True, upload_to='post_thumbnail/%Y/%m/%d/', verbose_name='サムネイル')),
                ('is_publick', models.BooleanField(default=True, verbose_name='公開可能か?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.Category', verbose_name='カテゴリ')),
                ('friend_posts', models.ManyToManyField(blank=True, related_name='_blog_friend_posts_+', to='news.Blog', verbose_name='関連記事')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='タイトル')),
                ('src', models.ImageField(help_text='送信後、一度保存してください。', upload_to='images/%Y/%m/%d/', verbose_name='画像')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.Blog', verbose_name='記事')),
            ],
        ),
    ]
